### ISSUE TITLE
add notification (error or debug output) when chrome reference is undefined

### ISSUE THREAD

**Issue by nicojanssens** [feross/chrome-dgram#11]
Minor request:

On line 23 you check if chrome is undefined before registering a handler to receive incoming incoming dgrams.

It would be useful to also have an else branch notifying that this registration did not taken place, by throwing an error or by generating some debug output.

I'm using chrome-dgram together with cordova-plugin-chrome-apps-sockets-udp in a cordova app, and a bug in my code was causing chrome-dgram to load before the cordova-plugin-chrome-apps-sockets-udp was properly initialised. So the chrome reference was undefined, and hence my app was able to send udp messages but it did not receive incoming messages. Having that else branch may have saved me some time debugging this issue ;-)

**Comment by feross** [comment]
Sounds good. We can throw in that case. Can you send a PR?

If you're interested, I can also add you as a collaborator to this repo, as I don't actually use this package in any apps that I maintain anymore and it could use some more maintainers in addition to the current ones.

**Comment by nicojanssens** [comment]
Thx. I sent a PR with a fix.

Happy to help you maintaining this repo. I'm actively using chrome-dgram and chrome-net in my [1tp](https://github.com/MicroMinion/1tp) lib, so I'm definitely interested in keeping this repo in good shape ;-)

**Comment by feross** [comment]
Fixed by https://github.com/feross/chrome-dgram/pull/12
