### ISSUE TITLE
Uncaught Type Error: Cannot read property 'udp' of undefined

### ISSUE THREAD

**Issue by RoKr93** [feross/chrome-dgram#4]
I've been attempting to use chrome-dgram with a JS browser application I've been writing. After compiling with Browserify and launching the application in a browser, there seems to be an error in line 23 of index.js: a Type Error is thrown because sockets appears to be undefined. Not sure what's up with this- as far as I know the chrome.sockets.udp call is just part of the Google sockets API, so I haven't really been able to figure out why it's acting up?

**Comment by feross** [comment]
Make sure you're running a new version of chrome. `chrome.sockets` is a newer API and wasn't available until about a year ago.

Also, more importantly, make sure that your app is requesting the proper permissions for chrome.sockers.
