### ISSUE TITLE
firefox-dgram -> Webtorrent as a firefox add-on?

### ISSUE THREAD

**Issue by DecipherCode** [feross/chrome-dgram#9]
Extraordinary work on webtorrent. I've been following its development since I started working on a javascript based bittorrent client([firebit](https://github.com/DecipherCode/Firebit)) a couple of years ago and you really have out done yourself. It seems that your very close to having webtorrent-**hybrid** running in chrome as an app. I thought you might be interested in moving in that direction for firefox as well.

I forked chrome-dgram. Its hacky but working: [firefox-dgram](https://github.com/DecipherCode/firefox-dgram)

Just letting you know. :package: :hammer:

**Comment by feross** [comment]
Nice work on `firefox-dgram`! Thanks for letting me know about it!
